baseURL = "https://docs.graphzen.com/"
languageCode = "en-us"
title = "GraphZen Documentation"

[menu]

  [[menu.main]]
    name = "Home"
    url = "https://graphzen.com"
    weight = -10

[[menu.main]]
    name = "Blog"
    url = "https://blog.graphzen.com"
    weight = -9

[[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/"
    weight = -8

[[menu.main]]
    name = "API"
    url = "https://api.graphzen.com"
    weight = -7
